'use client';
import {useEffect,useRef,useState} from 'react';
import {KNIVES} from './catalog';
import {configPrice,describeConfiguration,money,shippingQuote,type CartItem} from './configuration';
import Icon from './Icon';
type Props={items:CartItem[];onItems:(items:CartItem[])=>void;onClose:()=>void};
type Address={first:string;last:string;email:string;street:string;city:string;postal:string;country:string};
export default function Checkout({items,onItems,onClose}:Props){
 const dialog=useRef<HTMLDialogElement>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const [step,setStep]=useState(0);const [shipping,setShipping]=useState<'standard'|'express'>('standard');const [payment,setPayment]=useState<'card'|'paypal'|'bank'>('card');const [address,setAddress]=useState<Address>({first:'',last:'',email:'',street:'',city:'',postal:'',country:'IT'});const [sameBilling,setSameBilling]=useState(true);const [billing,setBilling]=useState('');const [busy,setBusy]=useState(false);
 const [receipt,setReceipt]=useState<{id:string;date:string;items:CartItem[];address:Address;shipping:string;payment:string;subtotal:number;delivery:number;total:number;billing:string}|null>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;dialog.current?.showModal();return()=>{if(timer.current)clearTimeout(timer.current);previous?.focus();};},[]);
 useEffect(()=>{dialog.current?.querySelector('.checkout-body')?.scrollTo({top:0});const heading=dialog.current?.querySelector<HTMLElement>('.checkout-heading');heading?.focus();},[step]);
 const displayed=receipt?.items??items;const subtotal=receipt?.subtotal??items.reduce((sum,item)=>sum+configPrice(item.knifeId,item.configuration)*item.quantity,0);const delivery=receipt?.delivery??shippingQuote(address.country,shipping,subtotal);const total=subtotal+delivery;
 const field=(key:keyof Address,value:string)=>setAddress(prev=>({...prev,[key]:value}));
 const submit=()=>{if(busy||!items.length)return;if(step<2){setStep(step+1);return;}setBusy(true);const order={id:`DEMO-${crypto.randomUUID().slice(0,8).toUpperCase()}`,date:new Date().toISOString(),items:structuredClone(items),address:{...address},shipping,payment,subtotal,delivery,total,billing:sameBilling?'Same as shipping':billing};timer.current=setTimeout(()=>{setReceipt(order);onItems([]);setBusy(false);setStep(3);},1100);};
 const exportReceipt=()=>{if(!receipt)return;const blob=new Blob([JSON.stringify({demo:true,paymentStatus:receipt.payment==='bank'?'awaiting_transfer_simulation':'simulated_paid',...receipt,items:receipt.items.map(({thumbnail,...item})=>item)},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${receipt.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <dialog ref={dialog} className="checkout-dialog" aria-label="Your configured knives and demo checkout" onCancel={e=>{e.preventDefault();if(!busy)onClose();}} onClick={e=>{if(e.target===dialog.current&&!busy)onClose();}}>
  <div className="checkout-shell"><header className="checkout-header"><span>MEMENTO / {receipt?'ORDER':'CHECKOUT'}</span><button type="button" onClick={onClose} disabled={busy} aria-label="Close checkout"><Icon name="x"/></button></header>
  <div className="demo-banner"><Icon name="lock" size={16}/><span>Demo checkout. No charge, payment or shipment is created.</span></div>
  {!receipt&&items.length>0&&<nav className="checkout-steps" aria-label="Checkout progress">{['Shipping','Payment','Review'].map((name,i)=><button key={name} disabled={i>=step||busy} className={step===i?'active':step>i?'complete':''} onClick={()=>setStep(i)} aria-current={step===i?'step':undefined}><span>{i<step?'✓':i+1}</span>{name}</button>)}</nav>}
  <div className="checkout-body" data-scroll>
   {displayed.length===0?<div className="empty-bag"><Icon name="shopping-bag" size={38}/><h2 className="checkout-heading" tabIndex={-1}>Your bag is waiting.</h2><p>Configure a knife and add it to your collection.</p><button className="primary-button" onClick={onClose}>Explore the collection <Icon name="arrow-right"/></button></div>:receipt?<div className="order-success"><div className="success-mark"><Icon name="check" size={34}/></div><p className="panel-eyebrow">{receipt.id}</p><h2 className="checkout-heading" tabIndex={-1}>Your design.<br/>Ready for the next step.</h2><p>{receipt.payment==='bank'?'Demo order recorded. Its simulated status is awaiting bank transfer.':'Your demo order is complete. The selected payment was simulated successfully.'}</p><div className="receipt-details"><span>{displayed.reduce((n,i)=>n+i.quantity,0)} item(s)</span><strong>{money(receipt.total)}</strong><span>Deliver to {receipt.address.first} {receipt.address.last}</span><span>{receipt.address.street}, {receipt.address.city}</span></div><button className="primary-button" onClick={exportReceipt}>Download demo order <Icon name="download"/></button><button className="text-button" onClick={onClose}>Return to showroom</button></div>:<form onSubmit={e=>{e.preventDefault();submit();}}>
    <div className="checkout-grid"><section className="checkout-form">
     <h2 className="checkout-heading" tabIndex={-1}>{['Where should it go?','Choose how to pay.','One final look.'][step]}</h2>
     {step===0&&<><div className="form-grid"><label>First name<input autoComplete="given-name" required value={address.first} onChange={e=>field('first',e.target.value)}/></label><label>Last name<input autoComplete="family-name" required value={address.last} onChange={e=>field('last',e.target.value)}/></label><label className="wide">Email<input type="email" autoComplete="email" required value={address.email} onChange={e=>field('email',e.target.value)}/></label><label className="wide">Street and house number<input autoComplete="street-address" required value={address.street} onChange={e=>field('street',e.target.value)}/></label><label>City<input autoComplete="address-level2" required value={address.city} onChange={e=>field('city',e.target.value)}/></label><label>Postcode<input autoComplete="postal-code" required pattern={address.country==='IT'?'[0-9]{5}':'[A-Za-z0-9 -]{3,12}'} title={address.country==='IT'?'Five digit postcode':'Enter a valid postcode'} value={address.postal} onChange={e=>field('postal',e.target.value)}/></label><label className="wide">Country<select autoComplete="country" value={address.country} onChange={e=>field('country',e.target.value)}><option value="IT">Italy</option><option value="FR">France</option><option value="DE">Germany</option><option value="ES">Spain</option><option value="NL">Netherlands</option></select></label></div><fieldset><legend>Delivery</legend>{(['standard','express'] as const).map(method=><label className="choice-card" key={method}><input type="radio" name="shipping" value={method} checked={shipping===method} onChange={()=>setShipping(method)}/><span><strong>{method==='standard'?'Standard delivery':'Express delivery'}</strong><small>{method==='standard'?'3–5 business days · demo estimate':'1–2 business days · demo estimate'}</small></span><em>{money(shippingQuote(address.country,method,subtotal))}</em></label>)}</fieldset><label className="check-label"><input type="checkbox" checked={sameBilling} onChange={e=>setSameBilling(e.target.checked)}/>Billing address is the same as shipping</label>{!sameBilling&&<label className="field-label">Billing name and full address<textarea required value={billing} onChange={e=>setBilling(e.target.value)} rows={3}/></label>}</>}
     {step===1&&<><fieldset className="payment-methods"><legend className="sr-only">Payment method</legend><label className="choice-card"><input type="radio" name="payment" checked={payment==='card'} onChange={()=>setPayment('card')}/><Icon name="credit-card"/><span><strong>Credit or debit card</strong><small>Visa / Mastercard · demo card</small></span></label><label className="choice-card"><input type="radio" name="payment" checked={payment==='paypal'} onChange={()=>setPayment('paypal')}/><Icon name="brand-paypal"/><span><strong>PayPal</strong><small>Simulated wallet authorisation</small></span></label><label className="choice-card"><input type="radio" name="payment" checked={payment==='bank'} onChange={()=>setPayment('bank')}/><Icon name="lock"/><span><strong>Bank transfer</strong><small>Order with pending payment status</small></span></label></fieldset>{payment==='card'?<div className="demo-card"><span>DEMO VISA</span><strong>4242 &nbsp; 4242 &nbsp; 4242 &nbsp; 4242</strong><div><span>DEMO CUSTOMER</span><span>12 / 30</span></div><small>Example card supplied. No real card details are collected.</small></div>:<div className="payment-note">{payment==='paypal'?'At confirmation, this demo simulates wallet authorisation.':'The demo order will be marked as awaiting payment. No bank details or transfer instructions are generated.'}</div>}</>}
     {step===2&&<div className="review-details"><section><h3>Shipping address <button type="button" onClick={()=>setStep(0)}>Edit</button></h3><p>{address.first} {address.last}<br/>{address.street}<br/>{address.postal} {address.city} · {address.country}<br/>{address.email}</p></section><section><h3>Delivery</h3><p>{shipping==='standard'?'Standard · 3–5 business days':'Express · 1–2 business days'}</p></section><section><h3>Payment <button type="button" onClick={()=>setStep(1)}>Edit</button></h3><p>{payment==='card'?'Demo Visa ending in 4242':payment==='paypal'?'PayPal · simulated authorisation':'Bank transfer · pending payment'}</p></section>{!sameBilling&&<section><h3>Billing address</h3><p>{billing}</p></section>}<label className="check-label"><input type="checkbox" required/>I understand this is a demonstration order with no actual payment or shipment.</label></div>}
    </section><aside className="order-summary"><h3>Your configuration <span>{items.reduce((n,i)=>n+i.quantity,0)}</span></h3>{items.map(item=>{const knife=KNIVES.find(k=>k.id===item.knifeId)!;return <article className="cart-item" key={item.id}><div className="cart-thumb">{item.thumbnail&&<img src={item.thumbnail} alt={`${knife.name} customised preview`}/>}</div><div><strong>{knife.name}</strong><small>{describeConfiguration(item.configuration)}</small>{item.configuration.decorations.map(d=><small key={d.id}>{d.type==='text'?`“${d.content}”`:d.content.replaceAll('-',' ')} · {d.treatment}</small>)}<b>{money(configPrice(item.knifeId,item.configuration))}</b><div className="quantity-control"><button type="button" disabled={item.quantity<=1||busy} onClick={()=>onItems(items.map(i=>i.id===item.id?{...i,quantity:i.quantity-1}:i))} aria-label={`Decrease ${knife.name} quantity`}><Icon name="minus" size={14}/></button><output>{item.quantity}</output><button type="button" disabled={item.quantity>=10||busy} onClick={()=>onItems(items.map(i=>i.id===item.id?{...i,quantity:i.quantity+1}:i))} aria-label={`Increase ${knife.name} quantity`}><Icon name="plus" size={14}/></button><button type="button" className="remove-item" disabled={busy} onClick={()=>onItems(items.filter(i=>i.id!==item.id))} aria-label={`Remove ${knife.name}`}><Icon name="trash" size={15}/></button></div></div></article>;})}<div className="totals"><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div><span>Shipping</span><strong>{delivery===0?'Included':money(delivery)}</strong></div><div className="grand-total"><span>Total</span><strong>{money(total)}</strong></div><small>Demonstration prices · VAT included</small></div><button type="submit" className="primary-button" disabled={busy}>{busy?'Processing demo order…':step===2?'Confirm demo order':step===0?'Continue to payment':'Review order'}<Icon name={busy?'lock':'arrow-right'}/></button>{step>0&&<button type="button" className="text-button" disabled={busy} onClick={()=>setStep(step-1)}>Back</button>}</aside></div>
   </form>}
  </div></div>
 </dialog>;
}
